name: AuthForm
description: Login APP built with Jaguer.
version: 0.0.1
homepage: https://github.com/Hexer10
author: Mattia <hexer504@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
    angular: ^5.0.0-beta+2
    angular_forms: ^2.0.0-beta+2
    angular_router: ^2.0.0-alpha+17
    http: ^0.11.0
    stream_transform: ^0.0.6
    angular_components: ^0.9.0-beta+1

dev_dependencies:
    angular_test: ^2.0.0-beta
    build_runner: ^0.9.2
    build_test: ^0.10.2
    build_web_compilers: ^0.4.1
